/**
 * This file was generated by the JPA Modeler
 */ 

package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author  RENAUD
 */

@Entity
@NamedQueries({
    @NamedQuery(
            name = "Modele.findByManufacturer",
            query = "SELECT m FROM Modele m WHERE m.constructeur.id = :id")
})
@XmlRootElement
public class Modele implements Serializable { 

    @Id
    private Long id;

    @Basic
    private String nom;

    @ManyToOne(targetEntity = Constructeur.class)
    private Constructeur constructeur;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public Constructeur getConstructeur() {
        return this.constructeur;
    }

    public void setConstructeur(Constructeur constructeur) {
        this.constructeur = constructeur;
    }

}
