/**
 * This file was generated by the JPA Modeler
 */ 

package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author  RENAUD
 */

@Entity
@NamedQueries({
    @NamedQuery(
            name = "Voiture.findByModele",
            query = "SELECT v FROM Voiture v WHERE v.modele.id = :id")
})
@XmlRootElement
public class Voiture implements Serializable { 

    @Id
    private Long id;

    @Basic
    private String annee;

    @Basic
    private String chevaux;

    @Basic
    private String carburant;

    @ManyToOne(targetEntity = Modele.class)
    private Modele modele;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAnnee() {
        return this.annee;
    }

    public void setAnnee(String annee) {
        this.annee = annee;
    }

    public String getChevaux() {
        return this.chevaux;
    }

    public void setChevaux(String chevaux) {
        this.chevaux = chevaux;
    }

    public String getCarburant() {
        return this.carburant;
    }

    public void setCarburant(String carburant) {
        this.carburant = carburant;
    }

    public Modele getModele() {
        return this.modele;
    }

    public void setModele(Modele modele) {
        this.modele = modele;
    }

}
